
INSERT INTO QUERY_LOAD (NUM, NUM2, NOTE) VALUES (0, 100, 'more_skip');
INSERT INTO QUERY_LOAD (NUM, NUM2, NOTE) VALUES (4, 104, 'more_skip');
INSERT INTO QUERY_LOAD (NUM, NUM2, NOTE) VALUES (9, 109, 'more_load');
INSERT INTO QUERY_LOAD (NUM, NUM2, NOTE) VALUES (5, 105, 'more_load');
