DROP TABLE QUERY_LOAD
CREATE TABLE QUERY_LOAD (
    NUM INT NOT NULL,
    NUM2 INT NOT NULL,
    NOTE TEXT
);

INSERT INTO QUERY_LOAD (NUM, NUM2, NOTE) VALUES (3, 103, 'first');
INSERT INTO QUERY_LOAD (NUM, NUM2, NOTE) VALUES (4, 104, 'first');
INSERT INTO QUERY_LOAD (NUM, NUM2, NOTE) VALUES (2, 102, 'first');
INSERT INTO QUERY_LOAD (NUM, NUM2, NOTE) VALUES (1, 101, 'first');
