DROP TABLE INT_LOAD
CREATE TABLE INT_LOAD (
    NUM INT NOT NULL,
    NOTE TEXT
);

INSERT INTO INT_LOAD (NUM, NOTE) VALUES (3, 'first');
INSERT INTO INT_LOAD (NUM, NOTE) VALUES (4, 'first');
INSERT INTO INT_LOAD (NUM, NOTE) VALUES (2, 'first');
INSERT INTO INT_LOAD (NUM, NOTE) VALUES (1, 'first');

