SPOOL data/temp.txt
SELECT ID, NUM, STR, VARSTR, TO_CHAR(DT, 'YYYY-MM-DD') AS DT, TO_CHAR(DTTM0, 'YYYY-MM-DD HH24:MI:SS') AS DTTM0, TO_CHAR(DTTM3, 'YYYY-MM-DD HH24:MI:SS.FF') AS DTTM3 FROM EMBULK_INPUT;
SPOOL OFF

EXIT;
