
INSERT INTO CHAR_LOAD (NAME, NOTE) VALUES ('A0', 'more_skip');
INSERT INTO CHAR_LOAD (NAME, NOTE) VALUES ('A4', 'more_skip');
INSERT INTO CHAR_LOAD (NAME, NOTE) VALUES ('A9', 'more_load');
INSERT INTO CHAR_LOAD (NAME, NOTE) VALUES ('A5', 'more_load');

