DROP TABLE CHAR_LOAD
CREATE TABLE CHAR_LOAD (
    NAME CHAR(2) NOT NULL,
    NOTE TEXT
);

INSERT INTO CHAR_LOAD (NAME, NOTE) VALUES ('A3', 'first');
INSERT INTO CHAR_LOAD (NAME, NOTE) VALUES ('A4', 'first');
INSERT INTO CHAR_LOAD (NAME, NOTE) VALUES ('A2', 'first');
INSERT INTO CHAR_LOAD (NAME, NOTE) VALUES ('A1', 'first');

